### ISSUE TITLE
Register a flysystem.mount_manager service

### ISSUE THREAD

**Issue by mathieuimbert** [WyriHaximus/pimple-flysystem-service#3]
I started using this handy service to handle file operations on different filesystems.

I need to be able to copy from one filesystem to another. It should use a [Mount Manager](http://flysystem.thephpleague.com/mount-manager/). I was thinking about adding a `$app['flysystem.mount_manager']`. Are you interested to add it to your repository? I can send you a pull request, otherwise I'll just register the service in my project.

**Comment by WyriHaximus** [comment]
Sure go for it. I'm not actively using it a lot my self anymore but I gladly welcome PR like this and continue to support it for those who use it 👍

**Comment by mathieuimbert** [comment]
Alright! I created pull request https://github.com/WyriHaximus/pimple-flysystem-service/pull/4.

**Comment by WyriHaximus** [comment]
Closed via #4
